name: 'renovate_stats_core'
description: 'Generates stats for the Renovate bot'
author: 'Anil Kulkarni'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  createdAfter:
    description: 'Only consider PRs created after this date'
    required: false
    default: ''

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'
  all:
    description: 'Full output for the repository'

runs:
  using: node20
  main: dist/index.js
