name: 'renovate_stats_core'
description: 'Generates stats for the Renovate bot'
author: 'Anil Kulkarni'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github_token:
    description: 'GitHub token, required to access the GitHub API'
    required: true
  created_after:
    description: 'Only consider PRs created after this date'
    required: false
    default: ''

# Define your outputs here.
outputs:
  packages:
    description: Dictionary of aggregate stats for every package
  reviewers:
    description:
      Dictionary of aggregate stats for all the PR's interacted with by each
      person
  status:
    description:
      Point-in-time aggregate status for number of PR's open, blocked, etc.
  timeline:
    description: A week-by-week aggregate of PR's opened and closed
  raw:
    description:
      'All the data collected by the action, useful for performing your own
      analysis'

runs:
  using: node20
  main: dist/index.js
